name: Generate data

on:
  schedule:
    - cron:  '*/5 * * * *'
  push:
  pull_request:

jobs:
  linux:
    strategy:
      matrix:
        swift_version: ['5.7']
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    container:
      image: swift:${{ matrix.swift_version }}
    steps:
      - uses: actions/checkout@v3
      - name: Configure git to trust the workspace despite the different owner
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build
        run: swift build -c release
      
      - name: Generate webview data
        run: |
          cd Data && ../.build/release/sn3 webview

      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit
        run: |
          git status | grep -qi Data/*.json && git add Data/*.json && git commit -m "Update data." && git push origin master